### ISSUE TITLE
Kick when reserved slots

### ISSUE THREAD

**Issue by flydvorkin** [TeamUlysses/ulx#109] opened 2017-09-10 15:11 UTC
### Steps to reproduce
1. Many tryes non-priveleged players to log on to server when reserved slots only if available
causes low server performance.

### Expected behavior
Need kick connected player when initial connect stage.

To resolve this - add hook for example:
hook.Add( "CheckPassword", "EXAMPLENAME", function( steamid64, ip, sv_password, cl_password, cl_name )
...
local SteamID = util.SteamIDFrom64(steamid64)
local access = false
if ULib.ucl.users[ sid ] then
	local group = ULib.ucl.users[ SteamID ].group
	while group do -- While group is not nil
		local groupInfo = ULib.ucl.groups[ group ]
		if not groupInfo then break end
		if table.HasValue( groupInfo.allow, "ulx reservedslots" ) then
			access = true
			break
		end
		if groupInfo.allow[ "ulx reservedslots" ] then
			access = true
			break
		end
		group = ULib.ucl.groupInheritsFrom( group )
	end
end
...
if access == false then
	if cur + slots >= max then
		return false, ( "[ULX] Reserved slot, sorry!" )
	end
end
...
end )

**Comment by flydvorkin** [comment] 2017-09-10 21:28
Check this code:
https://pastebin.com/Dg7ehvPx
This is work fine

**Comment by Nayruden** [comment] 2017-09-10 23:51
Duplicate of #8

**Closed by Nayruden** 2017-09-10 23:51 UTC
Labels: duplicate
