### ISSUE TITLE
GMod Update Error

### ISSUE THREAD

**Issue by MerlinStarfinder** [TeamUlysses/ulx#38] opened 2016-03-29 16:33 UTC
[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:46: attempt to index local 'txtCol' (a nil value)
  1. unknown - addons/ulx/lua/ulx/xgui/bans.lua:46
   2. include - [C]:-1
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:110
      5. fn - addons/ulib/lua/ulib/cl_init.lua:49
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

Today's gmod update seems to have removed the bans page.

**Comment by SticklyMan** [comment] 2016-03-29 16:34
Duplicate of #36

**Comment by MerlinStarfinder** [comment] 2016-03-29 16:34
sorry just saw that -_-

**Closed by SticklyMan** 2016-03-29 16:34 UTC
Labels: duplicate
