### ISSUE TITLE
Manually required to refresh server data for list to update in adverts

### ISSUE THREAD

**Issue by flleeppyy** [TeamUlysses/ulx#151] opened 2019-07-04 00:41 UTC
### Steps to reproduce
1. Edit/Add anything in Settings > Server
2. For me, I did Adverts.
3. Add an advert with anything
4. Click create

### Expected behavior
The list on the left should refresh and show the advert you added

### Actual behavior
It does not refresh, and requires the user to goto Client, and "Refresh server data"

### Version
Run "ulx version" in console and paste the result
ULib v2.63d (05/12/18)
ULX v3.73d (05/20/18)

**Comment by Nayruden** [comment] 2019-08-22 22:12
Are you getting any errors in the client or server console?

**Comment by zpetty33** [comment] 2022-08-06 00:34
Unable to reproduce this issue, without more info, and considering this ticket is so old, I am closing it.

**Closed by zpetty33** 2022-08-06 00:34 UTC
Labels: feedback
