### ISSUE TITLE
ULX Menu Commands Not Working

### ISSUE THREAD

**Issue by FadeTheLil** [TeamUlysses/ulx#136] opened 2018-07-22 19:03 UTC
### Steps to reproduce
1. install ULX
2. Log into server
3. Use menu commands

### Expected behavior
Tell us what should happen

When I use the commands in the ULX Menu, they should work normally, example.
!jail should jail the player, and I should be able to do this from the menu, not using the !jail text command.

### Actual behavior
Tell us what happens instead

When I try to use a command in the menu, I don't get an error, but the menu command doesn't work and all that it does is print the usage of the command in chat. 
For example, I go to "Fun" and use a command,
instead of actually working, it just prints the usage and the command in chat. It never did this before.

### Error(s) in server console, if any

[ERROR] addons/ulx/lua/ulx/xgui/server/sv_bans.lua:186: bad argument #1 to 'lower' (string expected, got nil)
  1. lower - [C]:-1
   2. unknown - addons/ulx/lua/ulx/xgui/server/sv_bans.lua:186
    3. unknown - addons/ulx/lua/ulx/modules/xgui_server.lua:72
     4. unknown - lua/includes/modules/concommand.lua:54

(even deleted this file "sv_bans.lua) and didnt get the error anymore, but the commands still didn't work, which leads me to think its an addon conflict 

### Error(s) in player's console, if any

None, nothing pops up here.

### Version
Run "ulx version" in console and paste the result

ULib v2.63
ULX v3.73

(I've tried reinstalling as well, no luck)
(and I also 100% reintalled it, deleted data, etc)

**Comment by jellyton69** [comment] 2018-09-03 00:03
I have also recently begun encountering this issue, no idea what the issue is.

**Comment by trollmad3** [comment] 2018-09-27 15:07
Have you tried a clean reinstall of ULX & ULib by deleting the data folders etc?

**Comment by mark27205** [comment] 2019-01-01 03:12
> Have you tried a clean reinstall of ULX & ULib by deleting the data folders etc?

... He said it.

**Comment by Nayruden** [comment] 2019-01-08 15:46
Which addon, @jellyton69?

**Comment by WilliamCTurner** [comment] 2019-04-15 13:32
I have been getting the same problem and I did do a fresh server reinstall and still won't work.

**Comment by trollmad3** [comment] 2019-04-17 16:06
@jellyton69 If this issue is fixed can you close it? Thanks.

**Comment by SticklyMan** [comment] 2019-04-17 21:24
While the primary issue can be caused by other addons or bad data, XGUI should handle it gracefully. I'll see what I can do about working around it when I get a chance.

**Comment by WilliamCTurner** [comment] 2019-04-18 10:54
On my server I had to reinstall the whole server with new gmod server files and it still won’t work.

**Comment by WilliamCTurner** [comment] 2019-04-18 10:54
[ULX] lua/ulx/xgui/server/sv_bans.lua:186: bad argument #1 to 'lower' (string expected, got nil)
  1. lower - [C]:-1
   2. unknown - lua/ulx/xgui/server/sv_bans.lua:186
    3. unknown - lua/ulx/modules/xgui_server.lua:72
     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by WilliamCTurner** [comment] 2019-04-18 10:55
Also when I try to use the menu for commands it only shows a usage in chat

**Comment by NubileEye** [comment] 2019-07-30 19:18
I am having the same issue on Enhanced Prop Hunt version K. I have installed, reinstalled, uninstalled many times and I am still unable to use the command "Mute" or "gimp". Muting does show command usage, but does not actually mute the player. Gimp doesn't replace their text under the predetermined array of text.

**Comment by NubileEye** [comment] 2019-08-21 04:51
I have managed to self RESOLVE my own issue. The issue was a shitty lua autorun I got from steam workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=297111172 | After removing this addon from my server, it started working again. Sorry for causing a false alarm. ULX and Ulib are essential, fundamental programs that vastly improve the servers they are implemented on. Thank you so much.

**Comment by Aholicknight** [comment] 2019-08-26 02:43
@FadeTheLil is this issue resolved?

**Comment by aezlfzmd** [comment] 2020-11-16 04:39
Bonjour j'ai un probléme avec mes groupe un superadmin a enlever tout les perm dans les groupe si quelqu'un sais comment je pourrais rénisialiser le menu ulx merci de bien vouloir de me répondre. (désoler pour mes fautes)

**Comment by Aholicknight** [comment] 2020-11-16 16:57
English translation: Hello I have a problem with my groups a superadmin to remove all the perms in the groups if anyone knows how I could renisialize the ulx menu please answer me. (sorry for my mistakes)

**Comment by aezlfzmd** [comment] 2020-11-17 17:02
j'ai fait pas mal de d'erreur mais j'étais fatigué se soir la si vous avez si il y a une commande qui permet de renisialiser le menu ulx merci de bien vouloir me répondre

**Comment by SticklyMan** [comment] 2024-07-19 23:59
I believe this is similar to #138, and it looks like the root cause is a conflicting addon. I've implemented a fix 07aafe3748f9d6c2fa70b67564eb5d8daae45f4b for the server error that somehow gets reported, and I'm hoping that helps XGUI be more resilient. If anyone continues to run into this problem, please submit a new issue!

**Closed by SticklyMan** 2024-07-19 23:59 UTC
Labels: bug
