### ISSUE TITLE
ULX Ban not working

### ISSUE THREAD

**Issue by PhilULSCI** [TeamUlysses/ulx#178] opened 2020-11-03 00:07 UTC
### Steps to reproduce
1. Use any method to ban a player
2. Give a specified duration
3. Execute the command

### Expected behavior
Tell us what should happen
**The player should be banned for a given time**
### Actual behavior
Tell us what happens instead
**Receive a message saying "Command 'ulx  ban', argument #3: invalid string**
### Error(s) in server console, if any
**None**
### Error(s) in player's console, if any
**None**
### Version
Run "ulx version" in console and paste the result
**ULX v3.73w**

**Comment by LifeDreamer24** [comment] 2021-05-03 02:52
Happens to me too :\

**Comment by zpetty33** [comment] 2022-08-05 23:56
Can anyone tell me if this is still an issue? I am not able to reproduce it.

**Comment by LifeDreamer24** [comment] 2022-08-06 01:57
I had the same issue about a year ago, I'll have to test it again to see if it persists.

**Comment by zpetty33** [comment] 2022-08-06 01:59
If you do get the issue, I will need as specific of instructions to recreate the problem as possible, as I am not able to replicate it.

**Comment by LifeDreamer24** [comment] 2022-08-06 02:08
If i remember well, it was only working with temporary bans.

Once the ban time was over, the prompt still showed and the ban was still active. The only difference was that the time left didn't showed up. It was saying something like: "Time left: " and nothing after.

Imma test it out later on as my hosting plamn is currently expired but you could try temp banning an alt and reconnecting after the time is over to see if it persists. Otherwise should be a problem on my side.

**Comment by zpetty33** [comment] 2024-07-14 19:45
Bans are working. Temp bans are broken for unbanning players at the end of the temp ban, but that is another issue and there currently is another issue open to address that issue. Closing this issue.

**Closed by zpetty33** 2024-07-14 19:45 UTC
Labels: investigation
