### ISSUE TITLE
[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:36: attempt to index local 'txtCol' (a nil value)

### ISSUE THREAD

**Issue by kradosser** [TeamUlysses/ulx#39] opened 2016-03-29 16:58 UTC
### Steps to reproduce
idk?

### Expected behavior
idk?

### Actual behavior
Tell us what happens instead

I just updatet my Garry's Mod Server to the newest version of gmod ([March 2016 Update](http://www.garrysmod.com/2016/03/29/march-2016-update/) ) and this popup, help! :c

### Error(s) in server console, if any

[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:36: attempt to index local 'txtCol' (a nil value)
  1. unknown - addons/ulx/lua/ulx/xgui/bans.lua:36
   2. include - [C]:-1
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:111
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:179
      5. fn - addons/ulib/lua/ulib/cl_init.lua:48
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

### Error(s) in player's console, if any

[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:36: attempt to index local 'txtCol' (a nil value)
  1. unknown - addons/ulx/lua/ulx/xgui/bans.lua:36
   2. include - [C]:-1
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:111
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:179
      5. fn - addons/ulib/lua/ulib/cl_init.lua:48
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

### Version
Run "ulx version" in console and paste the result

Invalid command entered. If you need help, please type "ulx help" in your console. (the latest.)

**Comment by SticklyMan** [comment] 2016-03-29 17:05
Duplicate of #36

**Closed by SticklyMan** 2016-03-29 17:05 UTC
Labels: duplicate
