### ISSUE TITLE
local txtCol a nil value

### ISSUE THREAD

**Issue by kem008** [TeamUlysses/ulx#36] opened 2016-03-23 18:11 UTC
### Steps to reproduce

1. Happens on first spawn.

### Expected behavior

No error should appear.

### Actual behavior

Error appeared on initialspawn

### Error(s) in server console, if any

No Server error

### Error(s) in player's console, if any

```
[ULX] Loading CLIENT module: motdmenu.lua
[ULX] Loading CLIENT module: uteam.lua
[ULX] Loading CLIENT module: xgui_client.lua
[ULX] Loading CLIENT module: xgui_helpers.lua
[ULX] Loading CLIENT module: xlib.lua
[ULX] Loading SHARED module: chat.lua
[ULX] Loading SHARED module: fun.lua
[ULX] Loading SHARED module: menus.lua
[ULX] Loading SHARED module: rcon.lua
[ULX] Loading SHARED module: teleport.lua
[ULX] Loading SHARED module: user.lua
[ULX] Loading SHARED module: userhelp.lua
[ULX] Loading SHARED module: util.lua
[ULX] Loading SHARED module: vote.lua

Client "[FP]ICEMAN" spawned in server <STEAM_0:1:4782422> (took 12 seconds).

[ERROR] addons/ulx/lua/ulx/xgui/bans.lua:46: attempt to index local 'txtCol' (a nil value)
  1. unknown - addons/ulx/lua/ulx/xgui/bans.lua:46
   2. include - [C]:-1
    3. fn - addons/ulx/lua/ulx/modules/cl/xgui_client.lua:142
     4. Call - addons/ulib/lua/ulib/shared/hook.lua:110
      5. fn - addons/ulib/lua/ulib/cl_init.lua:49
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

```

### Version
ulx 3.70d
ulib 2.60

**Comment by deinemudda32** [comment] 2016-03-29 15:37
Can confirm this.

**Comment by UnDeadClank** [comment] 2016-03-29 16:07
I have the same error? Anyone a hot fix?

**Comment by SticklyMan** [comment] 2016-03-29 16:11
What derma skin do you all currently have applied to XGUI?

**Comment by UnDeadClank** [comment] 2016-03-29 16:15
Default Derma Skin.
http://prntscr.com/alm1du

The Ban-Tab is missing too

**Comment by UnDeadClank** [comment] 2016-03-29 16:20
If i want change the skin, i have to reconnect. 
http://prntscr.com/alm3sr <- is that normal ?

**Comment by SticklyMan** [comment] 2016-03-29 16:27
Nope, that is not normal. A third party addon is probably causing that, but I don't think it should be a problem. Looks like a recent update caused this error- I'll hopefully have it fixed in a bit.

**Comment by UnDeadClank** [comment] 2016-03-29 16:28
This is the error i think:
http://prntscr.com/alm87x <- but i dont know a fix

**Comment by MerlinStarfinder** [comment] 2016-03-29 16:43
*Can confirm*

**Comment by qigdjmuz** [comment] 2016-03-29 16:47
Can confirm, seems to have been caused by the latest gmod update

**Comment by bigdogmat** [comment] 2016-03-29 16:49
@SticklyMan https://github.com/garrynewman/garrysmod/pull/1141

**Comment by UnDeadClank** [comment] 2016-03-29 16:57
ok i fix it for the moment. 
go in addons/ulx/lua/ulx/xgui/bans.lua
and change the txtCol.r , txtCol.g , txtCol.b the a Number.
http://prntscr.com/almmyb

**Comment by SticklyMan** [comment] 2016-03-29 17:02
Workaround pushed. It is a bug in the update, but this will supress the error in the meantime.
https://github.com/TeamUlysses/ulx/commit/11b3d931c6058040d44e77e39c5599b47457f63b

**Closed by SticklyMan** 2016-03-29 17:02 UTC

**Comment by KilljackTv** [comment] 2016-03-29 17:19
Well i am happy to see i am not the only person that has this issue.
