### ISSUE TITLE
Unknown Error(xgui)

### ISSUE THREAD

**Issue by deinemudda32** [TeamUlysses/ulx#14] opened 2015-12-31 06:52 UTC
[ERROR] addons/ulx/lua/ulx/xgui/commands.lua:316: attempt to call method 'Toggle' (a nil value)
1. unknown - addons/ulx/lua/ulx/xgui/commands.lua:316

Just appeard.

**Comment by Nayruden** [comment] 2016-02-02 12:31
What were you doing when you got this error?

**Comment by mcNuggets1** [comment] 2016-12-16 08:52
These sort of Errors do normally happen, when panels are getting invalid, due to closing the panel.

**Comment by SticklyMan** [comment] 2018-02-04 21:18
Completely unable to reproduce. If it keeps happening, I'll need a lot more info, as it looks to be some kind of race condition with data refreshing (like with permissions changing) while user interacts with the menu. Either that or auto-refreshing while developing third-party ULX commands. Either way, I'm at a loss for now.

**Closed by SticklyMan** 2018-02-04 21:18 UTC
Labels: invalid
