### ISSUE TITLE
Can't remove someones rank when they're off the server

### ISSUE THREAD

**Issue by TekBob** [TeamUlysses/ulx#49] opened 2016-06-02 07:31 UTC
This is an issue happening just to me I think, I need help fixing. When I remove someones rank when they're not on the server, when they join, they still have it, however, it doesn't show it anymore in the ULX menu. When they're on, I can remove their rank using ULX Removeuser. I've tried to remove their rank every way possible using ULX but they still have it.

### Error(s) in server console, if any
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: LoadFromBuffer: missing { in file In
(*AddonInfo*), 
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file In
AddonInfo, 
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file In
AddonInfo, 

### Error(s) in player's console, if any
- NOPE

### Version
ULib v2.60
ULX v3.70

**Comment by Nayruden** [comment] 2016-06-02 11:24
Please remove the user and run "ulx debuginfo" in your server console and
post the results here. Please point out who the target is.

**Comment by TekBob** [comment] 2016-06-02 17:10
ULX version: v3.70
ULib version: v2.60
Gamemode: DarkRP
Map: rp_downtown_v4c_v2
Dedicated server: true

Currently connected players:
Nick                            steamid            uid        id lsh
ExoTRAIN                        STEAM_0:0:140517270760757086  1  n	  
Baldur, Logi & friends [UK]     STEAM_0:0:54053101 1338767174 4  n	  
daddy                           STEAM_0:1:107772770138292678  5  n	  
Zaint1311                       STEAM_0:0:78696445 1362709839 6  n	  
Panda Panda Panda               STEAM_0:1:61477549 2914336221 7  n	  
Callum                          STEAM_0:1:45400793 3920991791 9  n	  
Harley $$$                      STEAM_0:0:1436317142398649755 10 n	  
ElkkuZombie22                   STEAM_0:0:88891919 4044128131 11 n	  
RIP MONEY---RIP SKINS           STEAM_0:0:1407697212042959930 12 n	  
TasiD                           STEAM_0:0:1736269021008087702 13 n	  
sharky                          STEAM_0:0:60222528 3252635114 14 n	  
Dr.Cloud                        STEAM_0:0:86342016 3088162623 15 n	  
Marco                           STEAM_0:0:1302895423755909505 18 n	  
GetMeHigh                       STEAM_0:0:1057036633657386971 19 n	  
mayor                           STEAM_0:0:1229237684126499112 20 n	  
J_05                            STEAM_0:1:1000601962578729057 21 n	  
Microsoft Word                  STEAM_0:1:32587766 2531642958 22 n	  
λlakuaku1                      STEAM_0:0:66822805 1843078992 24 n	  
Friendly Hobo HappE             STEAM_0:1:91230685 84451570   25 n	  
TAXI DRIVER                     STEAM_0:0:66140674 2686342048 26 n	  
Scrub Lord                      STEAM_0:0:28392932 232748838  27 n	  
OpticPusyetr                    STEAM_0:0:61076605 2994394422 28 n	  
jeff                            STEAM_0:1:74780235 1256942254 29 n	  
[red]xXLIVINGSOULXx             STEAM_0:0:1256630842755234331 32 n	  
Shane                           STEAM_0:1:21946428 947643455  35 n	  
Judy Hopps                      STEAM_0:1:1282191482079024794 36 n	  
underswap papyrus               STEAM_0:1:54277380 3485837444 38 n	  
E3z                             STEAM_0:0:1291728103734534973 41 n	  
ஜ۩ExplosiveDino۩ஜ         STEAM_0:1:95799379 3664225542 43 n	  
xSamboy                         STEAM_0:0:76912947 2708756190 44 n	  


ULib.ucl.users (#=18):
	STEAM_0:0:84898777:
		allow:
		name	=	★T.w² | EddieF#★
		deny:
		group	=	premium
	STEAM_0:1:31064918:
		deny:
		allow:
		name	=	Cody Evans
		group	=	superadmin
	STEAM_0:1:74780235:
		name	=	ThatCrazyScoutGuy
		deny:
		allow:
		group	=	admin
	STEAM_0:1:50136859:
		name	=	S P O D E R M A N
		deny:
		allow:
		group	=	operator
	STEAM_0:0:37984964:
		name	=	ArskaD44
		deny:
		allow:
		group	=	admin
	STEAM_0:0:173626902:
		name	=	T.w² | TasiD - CSGODanger.com
		deny:
		allow:
		group	=	superadmin
	STEAM_0:0:139479193:
		name	=	T.w² | TekBob
		deny:
		allow:
		group	=	superadmin
	STEAM_0:0:88891919:
		name	=	ElkkuZombie22
		deny:
		allow:
		group	=	moderatorpremium
	STEAM_0:1:92733221:
		name	=	Mark467
		deny:
		allow:
		group	=	moderator
	STEAM_0:1:128219148:
		allow:
		name	=	[MG] Judy Hopps
		deny:
		group	=	moderator
	STEAM_0:0:85595349:
		name	=	Richard Hammond
		deny:
		allow:
		group	=	vip
	STEAM_0:0:66822805:
		name	=	λlakuaku1
		deny:
		allow:
		group	=	admin
	STEAM_0:1:54443576:
		allow:
		name	=	Aiden™
		deny:
	STEAM_0:1:101752238:
		name	=	Dimzy
		deny:
		allow:
		group	=	premium
	STEAM_0:0:75445093:
		name	=	Azooz
		deny:
		allow:
		group	=	moderator
	STEAM_0:1:56649705:
		name	=	[AwpHeros] [NRG] [W-G] Bullseye
		deny:
		allow:
		group	=	premium
	STEAM_0:1:46175379:
		name	=	Charvey
		deny:
		allow:
		group	=	superadmin
	STEAM_0:1:56783918:
		allow:
		name	=	Donald Trump
		deny:
		group	=	premium


ULib.ucl.groups (#=12):
	moderatorvip:
		can_target	=	!%moderator
		allow:
		inherit_from	=	moderator
	operatorvip:
		can_target	=	!%moderator
		allow:
		inherit_from	=	operator
	user:
		allow:
			1	=	ulx asay
			2	=	ulx motd
			3	=	ulx psay
	superadmin:
		allow:
			1	=	awarn_delete
			2	=	awarn_options
			3	=	darkrp_changedoorsettings
			4	=	darkrp_setlicense
			5	=	darkrp_setmoney
			6	=	fpp_settings
			7	=	ulx addgroup
			8	=	ulx adduser
			9	=	ulx adduserid
			10	=	ulx banid
			11	=	ulx buddha
			12	=	ulx cac
			13	=	ulx cexec
			14	=	ulx cleardecals
			15	=	ulx clearragdolls
			16	=	ulx ent
			17	=	ulx exec
			18	=	ulx groupallow
			19	=	ulx groupdeny
			20	=	ulx hiddenecho
			21	=	ulx infammo
			22	=	ulx jumppower
			23	=	ulx limammo
			24	=	ulx listjoinsdcs
			25	=	ulx logchat
			26	=	ulx logdir
			27	=	ulx logecho
			28	=	ulx logechocolorconsole
			29	=	ulx logechocolordefault
			30	=	ulx logechocoloreveryone
			31	=	ulx logechocolormisc
			32	=	ulx logechocolorplayer
			33	=	ulx logechocolorplayerasgroup
			34	=	ulx logechocolors
			35	=	ulx logechocolorself
			36	=	ulx logevents
			37	=	ulx logfile
			38	=	ulx logjoinleaveecho
			39	=	ulx logspawns
			40	=	ulx logspawnsecho
			41	=	ulx luarun
			42	=	ulx map
			43	=	ulx maul
			44	=	ulx model
			45	=	ulx rcon
			46	=	ulx removegroup
			47	=	ulx removeuser
			48	=	ulx removeuserid
			49	=	ulx removezone
			50	=	ulx renamegroup
			51	=	ulx resetjumppower
			52	=	ulx setgroupcantarget
			53	=	ulx stopvote
			54	=	ulx userallow
			55	=	ulx userallowid
			56	=	ulx userdeny
			57	=	ulx userdenyid
			58	=	ulx version
			59	=	ulx veto
			60	=	ulx vote
			61	=	ulx voteban
			62	=	ulx voteecho
			63	=	ulx votekick
			64	=	ulx votemap
			65	=	ulx votemap2
			66	=	xgui_gmsettings
			67	=	xgui_managebans
			68	=	xgui_managegroups
			69	=	xgui_svsettings
		inherit_from	=	admin
	operator:
		allow:
			1	=	awarn_view
			2	=	awarn_warn
			3	=	ulx bring
			4	=	ulx goto
			5	=	ulx kick
			6	=	ulx noclip
			7	=	ulx return
			8	=	ulx seeasay
		can_target	=	!%moderator
		inherit_from	=	user
	moderator:
		can_target	=	!%moderator
		allow:
			1	=	awarn_view
			2	=	awarn_warn
			3	=	ulx ban
			4	=	ulx banid
			5	=	ulx bring
			6	=	ulx cloak
			7	=	ulx crash
			8	=	ulx crashban
			9	=	ulx freeze
			10	=	ulx gag
			11	=	ulx god
			12	=	ulx goto
			13	=	ulx jail
			14	=	ulx jailtp
			15	=	ulx kick
			16	=	ulx mute
			17	=	ulx noclip
			18	=	ulx nolag
			19	=	ulx physgunplayer
			20	=	ulx removezone
			21	=	ulx return
			22	=	ulx screengrab
			23	=	ulx seeasay
			24	=	ulx spectate
			25	=	ulx strip
			26	=	ulx uncloak
			27	=	ulx unfreeze
			28	=	ulx ungag
			29	=	ulx ungod
			30	=	ulx unjail
			31	=	ulx unmute
		inherit_from	=	operator
	premium:
		allow:
		inherit_from	=	user
	admin:
		can_target	=	!%admin
		allow:
			1	=	awarn_view
			2	=	awarn_warn
			3	=	darkrp_admincommands
			4	=	darkrp_getadminweapons
			5	=	darkrp_getjob_blackmarketdealer
			6	=	darkrp_getjob_drugdealer
			7	=	darkrp_getjob_heavygundealer
			8	=	darkrp_getjob_hitman
			9	=	darkrp_getjob_mayor
			10	=	darkrp_getjob_policechief
			11	=	darkrp_getjob_security
			12	=	darkrp_getjob_swat
			13	=	darkrp_getjob_swatgeneral
			14	=	darkrp_getjob_swatsniper
			15	=	darkrp_getjob_terrorist
			16	=	darkrp_getjob_thief
			17	=	darkrp_seeevents
			18	=	darkrp_setdoorowner
			19	=	fspectate
			20	=	fspectateteleport
			21	=	ulx armor
			22	=	ulx ban
			23	=	ulx banid
			24	=	ulx blind
			25	=	ulx bring
			26	=	ulx cleanprops
			27	=	ulx cloak
			28	=	ulx crash
			29	=	ulx crashban
			30	=	ulx csay
			31	=	ulx freeze
			32	=	ulx gag
			33	=	ulx gimp
			34	=	ulx god
			35	=	ulx goto
			36	=	ulx hp
			37	=	ulx ignite
			38	=	ulx jail
			39	=	ulx jailtp
			40	=	ulx kick
			41	=	ulx maul
			42	=	ulx mechatenabled
			43	=	ulx motdfile
			44	=	ulx motdurl
			45	=	ulx mute
			46	=	ulx noclip
			47	=	ulx nolag
			48	=	ulx physgunplayer
			49	=	ulx playsound
			50	=	ulx ragdoll
			51	=	ulx reconnect
			52	=	ulx removezone
			53	=	ulx return
			54	=	ulx rslots
			55	=	ulx rslotsmode
			56	=	ulx rslotsvisible
			57	=	ulx scale
			58	=	ulx screengrab
			59	=	ulx seeanonymousechoes
			60	=	ulx send
			61	=	ulx showmotd
			62	=	ulx slap
			63	=	ulx slay
			64	=	ulx spawnecho
			65	=	ulx spectate
			66	=	ulx sslay
			67	=	ulx stopsound
			68	=	ulx strip
			69	=	ulx teleport
			70	=	ulx tsay
			71	=	ulx unban
			72	=	ulx unblind
			73	=	ulx uncloak
			74	=	ulx unfreeze
			75	=	ulx ungag
			76	=	ulx ungimp
			77	=	ulx ungod
			78	=	ulx unignite
			79	=	ulx unigniteall
			80	=	ulx unjail
			81	=	ulx unmute
			82	=	ulx unragdoll
			83	=	ulx votebanminvotes
			84	=	ulx votebansuccessratio
			85	=	ulx votekickminvotes
			86	=	ulx votekicksuccessratio
			87	=	ulx votemap2minvotes
			88	=	ulx votemap2successratio
			89	=	ulx votemapenabled
			90	=	ulx votemapmapmode
			91	=	ulx votemapmintime
			92	=	ulx votemapminvotes
			93	=	ulx votemapsuccessratio
			94	=	ulx votemapvetotime
			95	=	ulx votemapwaittime
			96	=	ulx welcomemessage
			97	=	ulx whip
			98	=	ulx who
		inherit_from	=	moderator
	noaccess:
		allow:
		inherit_from	=	user
	vip:
		allow:
		inherit_from	=	user
	operatorpremium:
		can_target	=	!%moderator
		allow:
		inherit_from	=	operator
	moderatorpremium:
		can_target	=	!%moderator
		allow:
		inherit_from	=	moderator


ULib.ucl.authed (#=30):
	3252635114:
		group	=	user
		allow:
		deny:
		guest	=	true
	3734534973:
		group	=	user
		allow:
		deny:
		guest	=	true
	4044128131:
		name	=	ElkkuZombie22
		deny:
		allow:
		group	=	moderatorpremium
	4126499112:
		group	=	user
		allow:
		deny:
		guest	=	true
	3088162623:
		group	=	user
		allow:
		deny:
		guest	=	true
	3485837444:
		group	=	user
		allow:
		deny:
		guest	=	true
	2755234331:
		group	=	user
		allow:
		deny:
		guest	=	true
	2531642958:
		group	=	user
		allow:
		deny:
		guest	=	true
	2079024794:
		allow:
		name	=	[MG] Judy Hopps
		deny:
		group	=	moderator
	2914336221:
		group	=	user
		allow:
		deny:
		guest	=	true
	1843078992:
		name	=	λlakuaku1
		deny:
		allow:
		group	=	admin
	3755909505:
		group	=	user
		allow:
		deny:
		guest	=	true
	2708756190:
		group	=	user
		allow:
		deny:
		guest	=	true
	232748838:
		group	=	user
		allow:
		deny:
		guest	=	true
	947643455:
		group	=	user
		allow:
		deny:
		guest	=	true
	3920991791:
		group	=	user
		allow:
		deny:
		guest	=	true
	1338767174:
		group	=	user
		allow:
		deny:
		guest	=	true
	1008087702:
		name	=	T.w² | TasiD - CSGODanger.com
		deny:
		allow:
		group	=	superadmin
	760757086:
		group	=	user
		allow:
		deny:
		guest	=	true
	84451570:
		group	=	user
		allow:
		deny:
		guest	=	true
	3657386971:
		group	=	user
		allow:
		deny:
		guest	=	true
	138292678:
		group	=	user
		allow:
		deny:
		guest	=	true
	2994394422:
		group	=	user
		allow:
		deny:
		guest	=	true
	2042959930:
		group	=	user
		allow:
		deny:
		guest	=	true
	2686342048:
		group	=	user
		allow:
		deny:
		guest	=	true
	1256942254:
		name	=	ThatCrazyScoutGuy
		deny:
		allow:
		group	=	admin
	1362709839:
		group	=	user
		allow:
		deny:
		guest	=	true
	3664225542:
		group	=	user
		allow:
		deny:
		guest	=	true
	2398649755:
		group	=	user
		allow:
		deny:
		guest	=	true
	2578729057:
		group	=	user
		allow:
		deny:
		guest	=	true


Garrysmod default file (#=2):
	superadmin:
	admin:


Active workshop addons on this server:

Active legacy addons on this server:
3d_car_dealer_2                 
Adv. Duplicator 2                by Advanced Duplicator 2 Team: TB, emspike, version SVN (SVN)
APAnti                           by Author Name
:                                by :, version :
AWarn2                           by Mr.President, version 2.3
backup                          
blockhud                        
cac-release-20160521            
Climb SWEP 2                     by Unknown
customhq-shocker                
Customizable money printers      by husho
DarkRP Bank Robbery System       by Crap-Head, version 1 (2013)
darkrp_news                     
DarkRP Modification addon        by FPtje, version 1 (00/00/00)
Drugs Mod                        by Author Name
Ezio Auditore                    by Author Name
Fading door tool                 by Unknown
garrysmod-nlr-zone              
Gmod Legs 3                      by Author Name
Keypad Tool + Cracker            by Author Name
M9K Assault Rifles               by Unknown
CSS Weapons on M9K Base          by Unknown
M9K Heavy Weapons                by Unknown
m9k missing .wav                
M9K Small Arms pack              by Unknown
M9K Specialties                  by Unknown
Payday 2 NPCs and Player Models  by Unknown
PermaProps                       by Author Name
plogs-2                         
Precision Tool                   by Author Name
Pro Keypad Cracker               by Author Name
DarkRP Pro Lock Pick swep        by Author Name
prometheus                      
ULX Screengrab                   by Author Name
SmartSnap                        by Author Name
Spiderman's Swep!                by Author Name
Stacker STool                    by Unknown
steamgroup_rewards              
tdmcars_-_audi_113120185        
tdmcars_-_bmw_113118541         
tdmcars_-_bugatti_119146471     
tdmcars_-_cadillac_126920533    
tdmcars_-_chevrolet_113997239   
tdmcars_-_chrysler_176984840    
tdmcars_-_citroen_114000337     
tdmcars_-_dodge_114001545       
tdmcars_-_emergency_vehicles_pack_349281554
tdmcars_-_ferrari_119148996     
tdmcars_-_ford_113999373        
tdmcars_-_gmc_120766823         
tdmcars_-_holden_234464092      
tdmcars_-_honda_209683096       
tdmcars_-_hudson_120765874      
tdmcars_-_hummer_221198333      
tdmcars_-_jeep_224183198        
tdmcars_-_kia_226435666         
tdmcars_-_lamborghini_119148120 
tdmcars_-_land_rover_230680318  
tdmcars_-_mazda_233934024       
tdmcars_-_mclaren_217264937     
tdmcars_-_mercedes_131246684    
tdmcars_-_mini_123455501        
tdmcars_-_mitsubishi_131243694  
tdmcars_-_multi_brand_225810491 
tdmcars_-_murica_truck_pack_195481065
tdmcars_-_nissan_123455885      
tdmcars_-_pagani_254930849      
tdmcars_-_porsche_259899351     
tdmcars_-_scion_261961088       
tdmcars_-_shelby_1000_303809753 
tdmcars_-_subaru_266504181      
tdmcars_-_toyota_131245637      
tdmcars_-_vauxhall_272988660    
tdmcars_-_volkswagen_123456202  
tdmcars_-_volvo_286998866       
Terrorist Playermodels           by Author Name
3D2D Textscreens                 by Author Name
UK Police Playermodels           by Author Name
ULib                             by Team Ulysses, version 2.6 (02/15/16)
ULX                              by Team Ulysses, version 3.7 (02/15/16)
ULX Cleanup Kit                  by Author Name
UTime                            by Megiddo (Team Ulysses), version 1.44 (01/25/16)
VCMod ELS                        by freemmaann, version -
VCMod Main                       by freemmaann, version -


###------------------------------
His name is PinterHD and his rank was Admin. For some reason, it's not listed here, however, when re joined, he was still admin, yet when he's on, I can remove his rank using ULX.

**Comment by Nayruden** [comment] 2016-06-02 17:20
If you aren't having this issue with other players, try running in sandbox
to confirm that DarkRP/FAdmin isn't adding him.

**Comment by TekBob** [comment] 2016-06-02 17:30
It's with everyone with a rank

**Comment by TekBob** [comment] 2016-06-02 17:30
I removed like 10 of my in active admins and when some of them came on they still had it, so I investigated it with my friends and that was the issue.

I'll see if I can somehow disable fadmin

**Comment by TekBob** [comment] 2016-06-02 17:31
I mean I'll see if I disable fadmin if it will fix.

**Comment by TekBob** [comment] 2016-06-07 21:26
idk what the issue is, I can't disable fadmin, fucks my whole server. I really need this issue fixed as I need to demote a staff member and he knows about my ulx issue, I have a feeling that when I am off, he will come on and do something.

**Comment by Nayruden** [comment] 2016-06-12 17:59
Duplicate of #50 -- keeping that one and closing this one since there's more discussion there.

**Closed by Nayruden** 2016-06-12 17:59 UTC
Labels: duplicate
