### ISSUE TITLE
[ERROR] addons/ulib/lua/ulib/server/player_ext.lua:50: attempt to index local 'ply' (a nil value)

### ISSUE THREAD

**Issue by Zortex04** [TeamUlysses/ulx#34] opened 2016-03-16 07:12 UTC
### Steps to reproduce
1. Restart server?
2.^^
3.^^

### Expected behavior
Tell us what should happen Well I actully dont see anything happend ingame but the error is anoying

### Actual behavior
Tell us what happens instead ^^ 

### Error(s) in server console, if any

 
[ERROR] addons/ulib/lua/ulib/server/player_ext.lua:50: attempt to index local 'ply' (a nil value)
  1. fn - addons/ulib/lua/ulib/server/player_ext.lua:50
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:110
    3. CreateEntityFromTable - gamemodes/sandbox/gamemode/commands.lua:746
     4. unknown - lua/includes/modules/duplicator.lua:720
      5. ProtectedCall - [C]:-1
       6. Paste - lua/includes/modules/duplicator.lua:720
        7. fn - gamemodes/sandbox/gamemode/persistence.lua:41
         8. Run - addons/ulib/lua/ulib/shared/hook.lua:110
          9. fn - gamemodes/sandbox/gamemode/persistence.lua:54
           10. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
 

### Error(s) in player's console, if any

 
[ERROR] addons/ulib/lua/ulib/server/player_ext.lua:50: attempt to index local 'ply' (a nil value)
  1. fn - addons/ulib/lua/ulib/server/player_ext.lua:50
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:110
    3. CreateEntityFromTable - gamemodes/sandbox/gamemode/commands.lua:746
     4. unknown - lua/includes/modules/duplicator.lua:720
      5. ProtectedCall - [C]:-1
       6. Paste - lua/includes/modules/duplicator.lua:720
        7. fn - gamemodes/sandbox/gamemode/persistence.lua:41
         8. Run - addons/ulib/lua/ulib/shared/hook.lua:110
          9. fn - gamemodes/sandbox/gamemode/persistence.lua:54
           10. unknown - addons/ulib/lua/ulib/shared/hook.lua:110
 

### Version
Run "ulx version" in console and paste the result 3.70 something

The reason why i post this even thou it doesent relly do anything visualy ingame the error is anoying cause its spamming console

**Comment by Zortex04** [comment] 2016-03-16 07:13
^^ = Previous one

**Comment by AMD-NICK** [comment] 2016-03-16 12:39
**addons/ulib/**lua/ulib/server/player_ext.lua:50

**Comment by SticklyMan** [comment] 2016-03-29 17:05
Duplicate of #36

**Comment by SticklyMan** [comment] 2016-03-29 17:23
Whoops, I'm smoking something. This is not a duplicate as I had thought. :P

**Comment by Nayruden** [comment] 2016-05-19 22:50
Duplicate of #31 which was fixed a while ago, but hasn't been released yet (on GitHub only at the moment).

**Closed** 2016-05-21 14:19 UTC
Labels: duplicate
