### ISSUE TITLE
XGUI - Banning with invalid input will sometimes ban yourself

### ISSUE THREAD

**Issue by timmyws** [TeamUlysses/ulx#4] opened 2015-12-06 15:08 UTC
**Follow these steps to reproduce:**
Join an *empty* Garry's Mod server with ULib and ULX installed. Make yourself admin.
1. Open console and run `xgui xban` - *Opens a new ban window*
2. Click "Ban!" without changing any of the input fields.

Expected results: An error message.
Actual results: I get banned.
___
This is caused by [this](https://github.com/TeamUlysses/ulx/blob/master/lua/ulx/xgui/bans.lua#L385) line of code.
The name field is empty and `ULib.getUser("")` matches everyone, so it will return me even though I didn't enter a name, as long as there are no other players on the server.

**Comment by Nayruden** [comment] 2015-12-06 17:00
Addressed in https://github.com/TeamUlysses/ulib/commit/6c496ff084598f55d8adf8bf6a9383921c6ca195 from ULib. This stops this bug from happening, but I'll leave it to @SticklyMan if he wants to filter from XGUI, too. This leads to another question. @SticklyMan, why aren't you printing the error message getUser() hands you back in the derma message? That way the user has more context on what the issue is.

**Closed** 2016-01-26 02:39 UTC
Labels: bug
